version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: "@unform/web"
    versions:
    - 2.1.3
    - 2.1.4
    - 2.1.5
  - dependency-name: "@unform/core"
    versions:
    - 2.1.3
    - 2.1.4
    - 2.1.5
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: uuidv4
    versions:
    - 6.2.6
